spring:
    profile: dev
    application:
        name: microservicecloud-config-eureka-client
 
eureka:
    instance:
        hostname: eureka7001.com 
    client:
        register-with-eureka: false
        fetch-registy: false
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/
---
server:
    port: 7001
    
spring:
    profile: test
    application:
        name: microservicecloud-config-eureka-client
        
 eureka:
    instance:
        hostname: eureka7001.com
    client:
        register-with-eureka: false
        fetch-registy: false
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka/